#!/usr/bin/env python3
"""
Bootstrap a clean per-model workspace from a single GeoStudio model.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path


PIPELINE_DIR = Path(__file__).parent
PROJECT_ROOT = PIPELINE_DIR.parent
SRC_DIR = PROJECT_ROOT / "src"
sys.path.insert(0, str(SRC_DIR))

from artifact_paths import slugify
from model_catalog import discover_models, export_catalog
from model_workflow import _copy_full_xml_model, _extract_full_gsz_model


def _select_seed_analysis(model):
    analyses_with_points = [
        analysis for analysis in model.analyses if analysis.phreatic_surface.points
    ]
    if analyses_with_points:
        return max(
            analyses_with_points,
            key=lambda analysis: (len(analysis.phreatic_surface.points), analysis.analysis_name),
        )
    return model.analyses[0]


def _build_config_template(model, dataset_dir: Path, template_xml_path: Path) -> str:
    seed_analysis = _select_seed_analysis(model)
    points = sorted(seed_analysis.phreatic_surface.points, key=lambda point: (point.x, point.y))
    x_coordinates = [round(point.x, 6) for point in points]
    y_ranges = [
        {
            "min": round(point.y, 6),
            "max": round(point.y, 6),
            "baseline": round(point.y, 6),
        }
        for point in points
    ]
    point_names = [f"CP{i}" for i in range(1, len(points) + 1)]
    analysis_names = [analysis.analysis_name for analysis in model.analyses]

    return f'''"""
Per-model dataset config template generated by bootstrap_single_model.py.
Fill in the control point ranges before generating a dataset.
"""

MODEL_INFO = {{
    "project": "{model.section_name}",
    "section": "{model.model_name}",
    "description": "Dataset config for {model.model_name}",
    "units": "Model units",
    "version": "v1",
}}

MODEL_ANALYSES = {json.dumps(analysis_names, indent=4)}

CONTROL_POINTS = {{
    "count": {len(points)},
    "x_coordinates": {json.dumps(x_coordinates)},
    "names": {json.dumps(point_names)},
    "y_ranges": {json.dumps(y_ranges, indent=4)},
    "sync_groups": [],
    "interpolation": {{
        "n_total_points": {max(100, len(points))},
        "method": "pchip",
        "x_min": {min(x_coordinates) if x_coordinates else 0.0},
        "x_max": {max(x_coordinates) if x_coordinates else 0.0}
    }},
    "constraints": {{
        "enforce_flow_direction": True,
        "max_gradient": 2.0,
        "enforce_below_ground": True,
        "ground_clearance": 2.0
    }}
}}

GEOSTUDIO = {{
    "geocmd_location": "C:/Program Files/Seequent/GeoStudio 2024.1/Bin",
    "templates": {{
        "shallow": r"{template_xml_path}",
        "deep": r"{template_xml_path}"
    }},
    "fos_column_name": "SlipFOS",
    "solver": {{
        "retries": 3,
        "timeout_seconds": 300
    }}
}}

DATASET = {{
    "output_dir": r"{dataset_dir}",
    "version": "v1",
    "description": "{model.section_name} - {model.model_name}",
    "sampling": {{
        "method": "lhs",
        "random_seed": 42
    }},
    "checkpointing": {{
        "frequency": 10,
        "enabled": True
    }}
}}

CONFIG = {{
    "geostudio": {{
        "geocmd_location": GEOSTUDIO["geocmd_location"],
        "template_shallow": GEOSTUDIO["templates"]["shallow"],
        "template_deep": GEOSTUDIO["templates"]["deep"],
        "fos_column_name": GEOSTUDIO["fos_column_name"],
        "retries": GEOSTUDIO["solver"]["retries"],
        "timeout_seconds": GEOSTUDIO["solver"]["timeout_seconds"]
    }},
    "phreatic": {{
        "control_points": {{
            "points": [
                {{
                    "number": i + 1,
                    "x": CONTROL_POINTS["x_coordinates"][i],
                    "y_min": CONTROL_POINTS["y_ranges"][i]["min"],
                    "y_max": CONTROL_POINTS["y_ranges"][i]["max"],
                    "y_baseline": CONTROL_POINTS["y_ranges"][i]["baseline"],
                    "name": CONTROL_POINTS["names"][i]
                }}
                for i in range(CONTROL_POINTS["count"])
            ]
        }},
        "interpolation": CONTROL_POINTS["interpolation"],
        "constraints": CONTROL_POINTS["constraints"]
    }},
    "dataset": {{
        "n_samples": 100,
        "sampling_method": DATASET["sampling"]["method"],
        "output_dir": DATASET["output_dir"],
        "version": DATASET["version"],
        "description": DATASET["description"],
        "checkpoint_frequency": DATASET["checkpointing"]["frequency"],
        "random_seed": DATASET["sampling"]["random_seed"]
    }},
    "error_handling": {{
        "max_consecutive_failures": 20
    }},
    "logging": {{
        "log_dir": "logs",
        "level": "INFO"
    }},
    "system": {{
        "precision": 0.01,
        "rounding_decimals": 2
    }}
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description="Bootstrap a new dataset workspace from one GeoStudio model")
    parser.add_argument("--model-path", required=True, help="Path to a .gsz or top-level .xml model")
    parser.add_argument(
        "--output-root",
        default=str(PROJECT_ROOT / "output" / "model_bootstrap"),
        help="Root folder for bootstrap artifacts",
    )
    args = parser.parse_args()

    model_path = Path(args.model_path).resolve()
    output_root = Path(args.output_root).resolve()

    if not model_path.exists():
        print(f"Model not found: {model_path}")
        return 1

    models = discover_models(model_path.parent)
    matches = [model for model in models if Path(model.source_path).resolve() == model_path]
    if len(matches) != 1:
        print(f"Expected exactly one model for {model_path}, found {len(matches)}")
        return 1

    model = matches[0]
    model_root = slugify(model.model_name)
    workspace_root = output_root / model_root
    catalog_dir = workspace_root / "catalog"
    dataset_dir = workspace_root / "datasets" / model_root
    prepared_dir = workspace_root / "prepared_runs"
    trained_models_dir = workspace_root / "trained_models"
    template_model_dir = workspace_root / "template_model"
    config_path = workspace_root / "model_config.py"

    for path in (catalog_dir, dataset_dir, prepared_dir, trained_models_dir):
        path.mkdir(parents=True, exist_ok=True)

    if template_model_dir.exists():
        shutil.rmtree(template_model_dir)

    if model.source_type == "gsz":
        template_xml_path = _extract_full_gsz_model(Path(model.source_path), template_model_dir)
    else:
        template_xml_path = _copy_full_xml_model(Path(model.source_path), template_model_dir)

    outputs = export_catalog([model], catalog_dir)
    config_path.write_text(
        _build_config_template(model, dataset_dir, template_xml_path.resolve()),
        encoding="utf-8",
    )

    config = {
        "model": {
            "section_name": model.section_name,
            "model_name": model.model_name,
            "model_root_name": model_root,
            "source_path": model.source_path,
            "source_type": model.source_type,
            "analysis_count": len(model.analyses),
        },
        "paths": {
            "workspace_root": str(workspace_root),
            "catalog_json": str(outputs["catalog_json"]),
            "inputs_workbook": str(outputs["inputs_workbook"]),
            "model_config": str(config_path),
            "dataset_dir": str(dataset_dir),
            "prepared_runs_dir": str(prepared_dir),
            "trained_models_dir": str(trained_models_dir),
            "template_xml": str(template_xml_path.resolve()),
        },
    }

    bootstrap_config_path = workspace_root / "bootstrap_config.json"
    bootstrap_config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")

    print("=" * 70)
    print("MODEL BOOTSTRAP COMPLETE")
    print("=" * 70)
    print(f"Workspace:      {workspace_root}")
    print(f"Catalog JSON:   {outputs['catalog_json']}")
    print(f"Inputs XLSX:    {outputs['inputs_workbook']}")
    print(f"Model config:   {config_path}")
    print(f"Bootstrap JSON: {bootstrap_config_path}")
    print(f"Dataset dir:    {dataset_dir}")
    print(f"Template XML:   {template_xml_path.resolve()}")
    print(f"Model dir:      {trained_models_dir}")
    print("")
    print("Next:")
    print(f"  1. Update control point ranges in: {config_path}")
    print(f"  2. Generate dataset:")
    print(f"     python pipelines\\pipeline_generate_dataset.py --mode shallow --n_samples 100 --config-path \"{config_path}\"")
    print(f"  3. Train model:")
    print(f"     python pipelines\\train_models.py --dataset \"{dataset_dir}\" --mode shallow --output \"{trained_models_dir}\" --model-name \"{model_root}\"")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
