"""
Data Loader - Load and prepare datasets for ML training
"""

import json
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Tuple, Dict, List, Optional
from sklearn.model_selection import train_test_split
import logging

logger = logging.getLogger(__name__)


class FOSDataLoader:
    """
    Load FOS datasets generated by the pipeline.
    
    Handles both shallow and deep mode datasets.
    Prepares data for ML training.
    """
    
    def __init__(self, dataset_dir: str):
        """
        Args:
            dataset_dir: Directory containing shallow.csv and/or deep.csv
        """
        self.dataset_dir = Path(dataset_dir)
        
        if not self.dataset_dir.exists():
            raise FileNotFoundError(f"Dataset directory not found: {dataset_dir}")
        
        self.shallow_path = self.dataset_dir / "shallow.csv"
        self.deep_path = self.dataset_dir / "deep.csv"
        
        logger.info(f"Data loader initialized: {dataset_dir}")
    
    def load_mode(self, mode: str = 'shallow') -> pd.DataFrame:
        """
        Load dataset for specific mode.
        
        Args:
            mode: 'shallow' or 'deep'
            
        Returns:
            DataFrame with all samples
        """
        if mode == 'shallow':
            csv_path = self.shallow_path
        elif mode == 'deep':
            csv_path = self.deep_path
        else:
            raise ValueError(f"Invalid mode: {mode}")
        
        if not csv_path.exists():
            raise FileNotFoundError(f"Dataset not found: {csv_path}")
        
        df = pd.read_csv(csv_path)
        
        # Filter to successful samples only
        df_success = df[df['success'] == True].copy()
        
        logger.info(f"Loaded {mode} dataset:")
        logger.info(f"  Total samples: {len(df)}")
        logger.info(f"  Successful: {len(df_success)}")
        logger.info(f"  Failed: {len(df) - len(df_success)}")
        
        if len(df_success) == 0:
            raise ValueError(f"No successful samples in {mode} dataset!")
        
        return df_success
    
    def prepare_for_training(self, mode: str = 'shallow', 
                            test_size: float = 0.2,
                            val_size: float = 0.1,
                            random_state: int = 42) -> Dict[str, Tuple[np.ndarray, np.ndarray]]:
        """
        Prepare data for ML training with train/val/test splits.
        
        Args:
            mode: 'shallow' or 'deep'
            test_size: Fraction for test set (0.2 = 20%)
            val_size: Fraction of remaining for validation
            random_state: Random seed for reproducibility
            
        Returns:
            Dict with keys: 'train', 'val', 'test'
            Each value is tuple (X, y) where:
                X: Control point features [n_samples, 4]
                y: FOS values [n_samples]
        """
        # Load data
        df = self.load_mode(mode)
        
        # Extract features (4 control point Y values)
        # Extract features (all control point Y values - auto-detect)
        feature_cols = [c for c in df.columns if c.startswith('control_y_')]
        feature_cols.sort()  # Ensure correct order: control_y_1, control_y_2, etc.

        X = df[feature_cols].values

        print(f"  Detected {len(feature_cols)} control points: {feature_cols}")
        
        # Extract target (FOS)
        y = df['fos'].values
        
        logger.info(f"Extracted features:")
        logger.info(f"  X shape: {X.shape}")
        logger.info(f"  y shape: {y.shape}")
        logger.info(f"  FOS range: [{y.min():.3f}, {y.max():.3f}]")
        
        # Split: train / temp
        X_train, X_temp, y_train, y_temp = train_test_split(
            X, y, test_size=test_size + val_size, random_state=random_state
        )
        
        # Split temp into: val / test
        val_fraction = val_size / (test_size + val_size)
        X_val, X_test, y_val, y_test = train_test_split(
            X_temp, y_temp, test_size=(1 - val_fraction), random_state=random_state
        )
        
        logger.info(f"Data splits:")
        logger.info(f"  Train: {len(X_train)} samples ({len(X_train)/len(X)*100:.1f}%)")
        logger.info(f"  Val:   {len(X_val)} samples ({len(X_val)/len(X)*100:.1f}%)")
        logger.info(f"  Test:  {len(X_test)} samples ({len(X_test)/len(X)*100:.1f}%)")
        
        return {
            'train': (X_train, y_train),
            'val': (X_val, y_val),
            'test': (X_test, y_test)
        }
    
    def get_statistics(self, mode: str = 'shallow') -> Dict:
        """Get dataset statistics."""
        df = self.load_mode(mode)
        
        stats = {
            'n_samples': len(df),
            'fos': {
                'min': float(df['fos'].min()),
                'max': float(df['fos'].max()),
                'mean': float(df['fos'].mean()),
                'median': float(df['fos'].median()),
                'std': float(df['fos'].std())
            },
            'control_points': {}
        }
        
        # Stats for each control point
        feature_cols = [c for c in df.columns if c.startswith('control_y_')]
        feature_cols.sort()
        for col in feature_cols:
            stats['control_points'][col] = {
                'min': float(df[col].min()),
                'max': float(df[col].max()),
                'mean': float(df[col].mean())
            }
        
        return stats
    
    def get_full_phreatic_surfaces(self, mode: str = 'shallow', 
                                   max_samples: int = None) -> Tuple[np.ndarray, np.ndarray]:
        """
        Extract full 50-point phreatic surfaces (for advanced models).
        
        Returns:
            (X_surfaces, y_fos) where:
                X_surfaces: [n_samples, 50] - full phreatic Y values
                y_fos: [n_samples] - FOS values
        """
        df = self.load_mode(mode)
        
        if max_samples:
            df = df.head(max_samples)
        
        # Parse JSON phreatic surfaces
        surfaces = []
        for surf_json in df['phreatic_surface_y']:
            surf = json.loads(surf_json)
            surfaces.append(surf)
        
        X_surfaces = np.array(surfaces)
        y_fos = df['fos'].values
        
        logger.info(f"Extracted full phreatic surfaces:")
        logger.info(f"  Shape: {X_surfaces.shape} (samples × points)")
        
        return X_surfaces, y_fos


# ========================= UTILITY FUNCTIONS =========================

def print_dataset_info(dataset_dir: str, mode: str = 'shallow') -> None:
    """Quick dataset summary."""
    loader = FOSDataLoader(dataset_dir)
    
    try:
        stats = loader.get_statistics(mode)
        
        print("\n" + "="*70)
        print(f"📊 DATASET INFO - {mode.upper()} MODE")
        print("="*70)
        print(f"Location: {dataset_dir}")
        print(f"Samples: {stats['n_samples']}")
        print(f"\nFOS Statistics:")
        print(f"  Range: [{stats['fos']['min']:.3f}, {stats['fos']['max']:.3f}]")
        print(f"  Mean:  {stats['fos']['mean']:.3f}")
        print(f"  Std:   {stats['fos']['std']:.3f}")
        print(f"\nControl Point Ranges:")
        for cp_name, cp_stats in stats['control_points'].items():
            print(f"  {cp_name.upper()}: [{cp_stats['min']:.1f}, {cp_stats['max']:.1f}]")
        print("="*70)
        
    except FileNotFoundError as e:
        print(f"\n❌ Dataset not found: {e}")
        print(f"   Generate data first using pipeline_generate_dataset.py")


# ========================= TEST CODE =========================

if __name__ == "__main__":
    import sys
    
    # Test with your dataset
    dataset_dir = "data/datasets/fortknox_v1.0"
    
    if len(sys.argv) > 1:
        dataset_dir = sys.argv[1]
    
    print("="*70)
    print("🧪 DATA LOADER TEST")
    print("="*70)
    
    try:
        # Load and display info
        loader = FOSDataLoader(dataset_dir)
        
        # Test shallow mode
        print_dataset_info(dataset_dir, mode='shallow')
        
        # Prepare for training
        print("\n📚 Preparing training data...")
        data_splits = loader.prepare_for_training(mode='shallow')
        
        X_train, y_train = data_splits['train']
        X_val, y_val = data_splits['val']
        X_test, y_test = data_splits['test']
        
        print(f"\n✅ Data ready for ML training!")
        print(f"  Training set: {X_train.shape}")
        print(f"  Validation set: {X_val.shape}")
        print(f"  Test set: {X_test.shape}")
        
        # Sample data
        print(f"\n📋 Sample training data:")
        print(f"  X_train[0]: {X_train[0]}")
        print(f"  y_train[0]: {y_train[0]:.4f}")
        
    except FileNotFoundError as e:
        print(f"\n❌ {e}")
        print("\nGenerate data first:")
        print("  python pipelines\\pipeline_generate_dataset.py --mode shallow --n_samples 10")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
